CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255),
IDADE INT,
SERIE CHAR(255),
MATERIA CHAR(255),
NOTA DOUBLE,
PRIMARY KEY (ID)
);

SELECT * FROM TB_ALUNOS;

INSERT INTO TB_ALUNOS(NOME,IDADE,SERIE,MATERIA,NOTA) VALUES ("MARIA","10","5º","MATEMÁTICA","8.0");
INSERT INTO TB_ALUNOS(NOME,IDADE,SERIE,MATERIA,NOTA) VALUES ("ENZO","9","5º","MATEMÁTICA","9.0");
INSERT INTO TB_ALUNOS(NOME,IDADE,SERIE,MATERIA,NOTA) VALUES ("GAEL","10","5º","MATEMÁTICA","5.0");
INSERT INTO TB_ALUNOS(NOME,IDADE,SERIE,MATERIA,NOTA) VALUES ("LUA","9","5º","MATEMÁTICA","10.0");
INSERT INTO TB_ALUNOS(NOME,IDADE,SERIE,MATERIA,NOTA) VALUES ("CECÍLIA","10","5º","MATEMÁTICA","2.0");

SELECT * FROM TB_ALUNOS WHERE NOTA >7;
SELECT * FROM TB_ALUNOS WHERE NOTA <7;

UPDATE TB_ALUNOS SET NOTA = "3" WHERE ID = 5;