CREATE DATABASE DB_E_COMMERCE;

USE DB_E_COMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
FUNCAO CHAR(255),
COR CHAR(255),
TAMANHO CHAR(255),
MARCA CHAR(255),
VALOR DOUBLE,
PRIMARY KEY(ID)
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","BRANCO","PEQUENO","APPLE","1000");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","PRETO","MEDIO","APPLE","1100");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","VERMELHO","PEQUENO","SAMSUNG","400");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","PRETO","MEDIO","SAMSUNG","499");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","VERDE","GRANDE","XIAOMI","100");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","BRANCO","GRANDE","XIAOMI","400");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","PRETO","MEDIO","MOTOROLA","600");
INSERT INTO TB_PRODUTOS(FUNCAO,COR,TAMANHO,MARCA,VALOR) VALUES ("LIMPAR","BRANCO","PEQUENO","MOTOROLA","5000");

SELECT * FROM TB_PRODUTOS WHERE VALOR > 500;
SELECT * FROM TB_PRODUTOS WHERE VALOR < 500;

UPDATE TB_PRODUTOS SET COR = "ROSA", VALOR = "900" WHERE ID = 2;