CREATE DATABASE DB_CURSOS_DA_MINHA_VIDA;
USE DB_CURSOS_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
AREA CHAR(255), /*HUMANAS, BIOLOGIAS, EXATAS*/
DIFICULDADE CHAR(255),
PRIMARY KEY (ID)
);

CREATE TABLE TB_CURSOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255),
VALOR DOUBLE,
PROFESSOR CHAR(255),
DURACAO INT,
PRIMARY KEY(ID),
CTG_ID BIGINT,
FOREIGN KEY (CTG_ID) REFERENCES TB_CATEGORIAS(ID)
);

/*VISUALIZAÇÃO*/
SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_CURSOS;

INSERT INTO TB_CATEGORIAS(AREA,DIFICULDADE) VALUES ("HUMANAS","MÉDIA");
INSERT INTO TB_CATEGORIAS(AREA,DIFICULDADE) VALUES ("BIOLÓGICAS","BAIXA");
INSERT INTO TB_CATEGORIAS(AREA,DIFICULDADE) VALUES ("EXATAS","MÉDIA");
INSERT INTO TB_CATEGORIAS(AREA,DIFICULDADE) VALUES ("EXATAS","GRANDE");
INSERT INTO TB_CATEGORIAS(AREA,DIFICULDADE) VALUES ("TECNÓLOGO","MÉDIA");

INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("JAVA",0.00,"GEANDRO",3,5);
INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("LEITURA",200.00,"AIMÉE",1,1);
INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("PLANTAÇÃO",400.00,"JEFF",6,2);
INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("AERONAUTICA",10000.00,"PAULA",53,4);
INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("LOGICA",150.00,"PRISCILA",2,3);
INSERT INTO TB_CURSOS(NOME,VALOR,PROFESSOR,DURACAO,CTG_ID) VALUES ("VETERINARIA",130000.00,"ROBERTA",48,4);

SELECT * FROM TB_CURSOS WHERE VALOR > 500;
SELECT * FROM TB_CURSOS WHERE VALOR > 600 AND VALOR < 1000;
SELECT * FROM TB_CURSOS WHERE NOME LIKE "%J%";

SELECT * FROM TB_CATEGORIAS INNER JOIN TB_CURSOS ON TB_CATEGORIAS.ID = TB_CURSOS.CTG_ID;
SELECT * FROM TB_CATEGORIAS INNER JOIN TB_CURSOS ON TB_CATEGORIAS.ID = TB_CURSOS.CTG_ID WHERE AREA LIKE "EXATAS";


