CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
RECEITA_OBRIGATORIA CHAR(255),
GENERICO CHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255),
PARA CHAR(255),
MARCA CHAR(255),
VALOR DOUBLE,
PRIMARY KEY (ID),
CTG_ID BIGINT,
FOREIGN KEY (CTG_ID) REFERENCES TB_CATEGORIAS (ID)
);

/*VISUALIZAÇÃO*/
SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CATEGORIAS(RECEITA_OBRIGATORIA,GENERICO) VALUES ("SIM", "SIM");
INSERT INTO TB_CATEGORIAS(RECEITA_OBRIGATORIA,GENERICO) VALUES ("SIM", "NÃO");
INSERT INTO TB_CATEGORIAS(RECEITA_OBRIGATORIA,GENERICO) VALUES ("NÃO", "NÃO");
INSERT INTO TB_CATEGORIAS(RECEITA_OBRIGATORIA,GENERICO) VALUES ("NÃO", "SIM");

INSERT INTO TB_PRODUTOS(NOME,PARA,MARCA,VALOR,CTG_ID) VALUES ("DRAMIN","ENJOO","HYPERA","18.00",3);
INSERT INTO TB_PRODUTOS(NOME,PARA,MARCA,VALOR,CTG_ID) VALUES ("DORIL","DOR DE CABEÇA","HYPERA","15.00",3);
INSERT INTO TB_PRODUTOS(NOME,PARA,MARCA,VALOR,CTG_ID) VALUES ("AMYTRIL","DEPRESSÃO","CRISTÁLIA","56.00",2);
INSERT INTO TB_PRODUTOS(NOME,PARA,MARCA,VALOR,CTG_ID) VALUES ("AMYTRIL","DEPRESSÃO","CRISTÁLIA","48.00",1);
INSERT INTO TB_PRODUTOS(NOME,PARA,MARCA,VALOR,CTG_ID) VALUES ("DIPIRONA","ANTITERMICO","MEDLEY","10.00",4);

SELECT * FROM TB_PRODUTOS WHERE VALOR > 50;
SELECT * FROM TB_PRODUTOS WHERE VALOR > 5 AND VALOR <60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";

SELECT * FROM TB_CATEGORIAS INNER JOIN TB_PRODUTOS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CTG_ID;
SELECT * FROM TB_CATEGORIAS INNER JOIN TB_PRODUTOS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CTG_ID WHERE GENERICO LIKE "SIM";
